---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: php
  
- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined
  tags: php
  
- name: Define extra php_packages.
  set_fact:
    php_packages: "{{ php_packages | list + php_packages_extra | list }}"
  when: php_packages_extra is defined
  tags: php
  
- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined
  tags: php
  
- name: Define php_conf_paths.
  set_fact:
    php_conf_paths: "{{ __php_conf_paths }}"
  when: php_conf_paths is not defined
  tags: php
  
- name: Define php_extension_conf_paths.
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined
  tags: php

- name: Define php_fpm_conf_path.
  set_fact:
    php_fpm_conf_path: "{{ __php_fpm_conf_path }}"
  when: php_fpm_conf_path is not defined
  tags: php

# Setup/install tasks.
- include: setup-debian.yml
  when: (php_install_from_source == false) and (ansible_os_family == 'Debian')
  static: no
  tags: php
  
# Install PHP from source when php_install_from_source is true.
- include: install-from-source.yml
  when: php_install_from_source == true
  static: no
  tags: php
  
# Configure PHP.
- include: configure.yml
  static: no
  tags: php  
  
- include: configure-fpm.yml
  static: no
  tags: php

- include: composer.yml
  static: no
  when: php_install_composer
  tags: php
